# Generated by Django 5.0.1 on 2024-03-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='fromadd',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='to',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
