# Generated by Django 5.0.1 on 2024-03-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_appointment_fromadd_appointment_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentDischargeDetails',
        ),
    ]
